version: '3'
networks:
  red:
    driver: bridge
  blue:
    driver: bridge
services:
  red1:
    build:
      context: .
      dockerfile: base.docker
    environment:
      SERVER_NAME: red1
    networks:
     - red
  red2:
    build:
      context: .
      dockerfile: base.docker
    environment:
      SERVER_NAME: red2
    networks:
     - red  
  blue1:
    build:
      context: .
      dockerfile: base.docker
    environment:
      SERVER_NAME: blue1
    networks:
     - blue
  blue2:
    build:
      context: .
      dockerfile: base.docker
    environment:
      SERVER_NAME: blue2
    networks:
     - blue
  hub:
    build:
      context: .
      dockerfile: base.docker
    environment:
      SERVER_NAME: hub
    networks:
     - red
     - blue
  